run:
  skip-dirs:
    - doc
    - testdata
  tests: false

linters:
  disable:
    # - lll
    # - maligned
    # - gochecknoglobals
    # - gochecknoinits
    - godox
    # - goconst
    # - bodyclose
  # presets:
  #     - bugs
  #     - complexity
  #     - format
  #     - performance
  #     - style
  #     - unused

linters-settings:
  misspell:
    ignore-words:
      - restricteds
  funlen:
    lines: 80
    statements: 45