version: "2"
run:
  tests: false
linters:
  disable:
    - godox
  settings:
    funlen:
      lines: 80
      statements: 45
    misspell:
      ignore-rules:
        - restricteds
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - doc$
      - testdata$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - doc$
      - testdata$
