version: "3.7"

services:
  villip:
    build:
      context: ./..
    environment:
      VILLIP_FOLDER: "/conf"
      VILLIP_URL: "http://smocker:8080"
      VILLIP_PRIORITY: 1
      VILLIP_DEBUG: 1
      VILLIP_FROM: book
      VILLIP_TO: smartphone
      VILLIP_FOR: /get/youngster,/get/children,/post/youngster,/post/children
      VILLIP_FROM_1: sing
      VILLIP_TO_1: chat
      VILLIP_FOR_1: /get/youngster,/get/children,/post/youngster,/post/children
      VILLIP_FROM_2: videogame
      VILLIP_TO_2: boardgame
      VILLIP_FOR_2: /get/boomer,/get/grandparent,/post/boomer,/post/grandparent
      VILLIP_TYPES: text/html,text/plain
      VILLIP_FROM_3: take
      VILLIP_TO_3: Bring
      VILLIP_PREFIX_FROM: /
      VILLIP_PREFIX_TO: /env/
    volumes:
      - "./villip:/conf"
    networks:
      - villip_test
  venom:
    build:
      context: ./venom
    environment:
      VENOM_VAR_VILLIP_SERVER: "villip"
      VENOM_VAR_VILLIP_PORT1: "8080"
      VENOM_VAR_VILLIP_PORT2: "8081"
      VENOM_VAR_VILLIP_PORT3: "8082"
    volumes:
      - "./tests:/testsuite"
      - "./outputs:/outputs"
      - tcpoutput:/tcpoutput
    networks:
      - villip_test
  smocker:
    build:
      context: smocker
    volumes:
      - "./mocks:/mocks"
      - tcpoutput:/tcpoutput
    networks:
      - villip_test
    # ports:
    #   - 8081:8081
  tcpserver:
    build:
      context: ./tcp/server
    networks:
      - villip_test
  tcpclient:
    build:
      context: ./tcp/client
    networks:
      - villip_test
    volumes:
      - tcpoutput:/tcpoutput

networks:
  villip_test:

volumes:
  tcpoutput:
