version: "3.7"

services:
  villip:
    build:
      context: ./..
    environment:
      VILLIP_FOLDER: "/conf"
      VILLIP_URL: "http://smocker:8080"
      VILLIP_PRIORITY: 1
      VILLIP_DEBUG: 1
      VILLIP_FROM: book
      VILLIP_TO: smartphone
      VILLIP_FOR: /youngster,/children
      VILLIP_FROM_1: videogame
      VILLIP_TO_1: boardgame
      VILLIP_FOR_1: /boomer,/grandparent
      VILLIP_FROM_2: sing
      VILLIP_TO_2: chat
      VILLIP_FOR_2: /youngster,/children
      VILLIP_TYPES: text/html,text/plain
      VILLIP_FROM_3: take
      VILLIP_TO_3: Bring
      VILLIP_PREFIX_FROM: /
      VILLIP_PREFIX_TO: /env/
    volumes:
      - "./villip:/conf"
    networks:
      - villip_test
  venom:
    build:
      context: ./venom
    environment:
      VENOM_VAR_VILLIP_SERVER: "villip"
      VENOM_VAR_VILLIP_PORT1: "8080"
      VENOM_VAR_VILLIP_PORT2: "8081"
    volumes:
      - "./tests:/testsuite"
      - "./outputs:/outputs"
    networks:
      - villip_test
  smocker:
    build:
      context: smocker
    volumes:
      - "./mocks:/mocks"
    networks:
      - villip_test
    # ports:
    #   - 8081:8081

networks:
  villip_test:
