---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tcpoutput
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: /tmp/k8svillip
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tcpoutput
spec:
  volumeName: pv-tcpoutput
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tcpclient
  labels:
    app.kubernetes.io/name: tcpclient
spec:
  template:
    spec:
      containers:
      - name: tcpclient
        image: tcpclient
        imagePullPolicy: Never # Force to use the image loaded in kind
        volumeMounts:
        - name: tcpoutput
          mountPath: /tcpoutput
        ports:
          - containerPort: 8080
      volumes:
      - name: tcpoutput
        persistentVolumeClaim:
          claimName: pvc-tcpoutput
      restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: tcpserver
  labels:
    app.kubernetes.io/name: tcpserver
spec:
  containers:
  - name: tcpserver
    image: tcpserver
    imagePullPolicy: Never # Force to use the image loaded in kind
    ports:
      - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
spec:
  selector:
    app.kubernetes.io/name: tcpserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888