---
apiVersion: v1
kind: ConfigMap
metadata:
  name: villip-env
data:
      VILLIP_FOLDER: "/conf"
      VILLIP_URL: "http://smocker:8080"
      VILLIP_PRIORITY: "1"
      VILLIP_DEBUG: "1"
      VILLIP_FROM: book
      VILLIP_TO: smartphone
      VILLIP_FOR: /get/youngster,/get/children,/post/youngster,/post/children
      VILLIP_FROM_1: sing
      VILLIP_TO_1: chat
      VILLIP_FOR_1: /get/youngster,/get/children,/post/youngster,/post/children
      VILLIP_FROM_2: videogame
      VILLIP_TO_2: boardgame
      VILLIP_FOR_2: /get/boomer,/get/grandparent,/post/boomer,/post/grandparent
      VILLIP_TYPES: text/html,text/plain
      VILLIP_FROM_3: take
      VILLIP_TO_3: Bring
      VILLIP_PREFIX_FROM: /
      VILLIP_PREFIX_TO: /env/
---
apiVersion: v1
kind: Pod
metadata:
  name: villip
  labels:
    app.kubernetes.io/name: villip
spec:
  containers:
  - name: villip
    image: villip
    imagePullPolicy: Never # Force to use the image loaded in kind
    volumeMounts:
    - name: config
      mountPath: /conf
    ports:
      - containerPort: 8080
      - containerPort: 8081
      - containerPort: 8082
      - containerPort: 8888
    envFrom:
      - configMapRef:
          name: villip-env
  volumes:
  - name: config
    configMap:
      name: villip-conf
---
apiVersion: v1
kind: Service
metadata:
  name: villip
spec:
  selector:
    app.kubernetes.io/name: villip
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: smocker1
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: smocker2
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: smocker3
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: binary